# Numpy - Numerical Python
**In 2005, Travis Oliphant created NumPy by incorporating features of the competing Numarray into Numeric, with extensive modifications.**
1. Array creation and storage and all related functions
2. Laplace, fourier advance maths and linear algebra
3. Random numbers

----

- Speed
- Less Memory
- Easy Math Operations
- Used in data science / Machine Learning (AI) / DS / DA
- also in stock market , medical research, image precessing and more

@pip install numpy

----

  | Description   | List                          | Numpy                         |
  |---------------|-------------------------------|-------------------------------|
  | Speed         | Slow                          | 50-100 times faster           |
  | Memory        | Uses more                     | uses less                     |
  | Calculations  | need loops                    | instant calculations          |
  | which is best | if working with small dataset | if working with large dataset |
---

In [3]:
import numpy as np

In [21]:
temp_array = np.array([120,130,123,145,163,90,89])

In [22]:
average = np.mean(temp_array)
print(average)

122.85714285714286


In [23]:
python_list = [1, 2, 3, 5, 6]
print(python_list)

[1, 2, 3, 5, 6]


In [24]:
numpy_array = np.array([1, 2, 3, 5, 6])
print(numpy_array)

[1 2 3 5 6]


## Arrays

### Properties of array
1. Shape,size,type

In [19]:
arr__2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr__2d.shape)  # Showing 2 Rows and 3 Columns 
print(arr__2d.size)   # Shows number of elements
print(arr__2d.ndim)   # number of dimensions
print(arr__2d.dtype)  # Data type of array elements

(2, 3)
6
2
int64


In [17]:
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3],[4,5,6]])
arr3 = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(arr1.ndim)   # 1 dimensional array
print(arr2.ndim)   # 2 dimensional array
print(arr3.ndim)   # 3 dimensional array

1
2
3


### Conversion of Data type in array

In [22]:
array = np.array([1.2,2.3,3.4])
int_arr = array.astype(int)  # change array float to int data type
print(array.dtype)
print(int_arr)
print(int_arr.dtype)

float64
[1 2 3]
int64


### Array Dimensions

In [25]:
#one-dimensional array
ar_1d = np.array([1,2,3,4,5])
print(ar_1d)

[1 2 3 4 5]


In [28]:
# two-dimensional array
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [32]:
# Multi- dimensional array
# Matrix

matrix = np.array([[2,3,4],
                   [35,45,57]])
print(matrix)

[[ 2  3  4]
 [35 45 57]]


In [33]:
# Creating arrays from python lists
# np.array([ele1, ele2, ele3])

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [35]:
# with default values
# np.zeros(shape) (3) fir 1d, (3,3) 2d

zeroes_array = np.zeros(3)
print(zeroes_array)

[0. 0. 0.]


In [36]:
#ones(shape)
ones_array =  np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [38]:
# full(shape,value)
filled_array = np.full((4,3),8)
print(filled_array)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [41]:
# Creating sequences of numbers in numpy
# arange(start, stop, step)
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [43]:
# creating identity matrices
# eye(size)

identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Mathemetical operations using array/numpy

|OPERATORS |EXAMPLES |
|----------|---------|
|+         | array+2 |
|-         | array-2 |
|*         | array*2 |
|/         | array/2 |
|**        | array**2|
|//        | array//2|
|%         | array%2 |

In [27]:
import numpy as np
arr = np.array([10,20,30])
print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr ** 5)

[15 25 35]
[ 5 15 25]
[ 50 100 150]
[  100000  3200000 24300000]


### Aggregation Function
| FUNCTION       | WHAT IT DOES                      |
|----------------|-----------------------------------|
| np.sum(array)  | add all elements                  |
| np.mean(array) | Calculate Average                 |
| np.min(array)  | Represent smallest value          |
| np.max(array)  | represent maximum value           | 
| np.std(array)  | call out Standard deviation value | 
| np.var(array)  | Calculate Variance                | 

In [29]:
arr = np.array([10,20,30,40,50])
# Calculating Aggregation functions
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
50
14.142135623730951
200.0


### Indexing 
selecting specific element from the array
- positive indexing ( left to right )
- Negative indexing ( right to left )
  
  ``` python
  array[index] #1d array
  array[row, column] #2d array
  ```
  
### Fancy indexing 
Selecting multiple elements at once

### Slicing 
Extracting subset or sub-arrays

```python
array[start:stop:step]
```
### Boolean Masking (T/F)
filter elements on conditional based


In [33]:
#Indexing 
arr = np.array([10,20,30,40,50])
print (arr[0])
print (arr[3])
print (arr[-1])

10
40
50


In [38]:
#Slicing
print(arr[1:5])
print(arr[:4])
print(arr[::2]) 
print(arr[::-1])
print(arr[1::2])

[20 30 40 50]
[10 20 30 40]
[10 30 50]
[50 40 30 20 10]
[20 40]


In [39]:
#Fancy Indexing 
print(arr[[0, 2, 4]])

[10 30 50]


In [42]:
#Boolean Masking
print(arr[arr>25])

[30 40 50]


### Reshaping and manipulating arrays
- Changing dimensions(shape) withing modifying an array
- it doesn't create a copy, it returns a view
- Only if dimensions match
- Syntax
  ```python
  arr.reshape(rows,columns)
  ```

In [45]:
arr = np.array([1,2,3,4,5,6])
reshape_arr = arr.reshape(2,3)
print(reshape_arr)

[[1 2 3]
 [4 5 6]]


### Flattening Arrays
Converting Multi-dimensional array into 1d array
- flatten
  ```python
  .flatten() # -> copy
  ```
- ravel
  ```python
  .ravel() # -> view
  ```

In [47]:
arr_2d = np.array([[1,2,3],
                  [4,5,6]])
print(arr_2d.flatten())
print(arr_2d.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


### Advanced Numpy
|||
|------------|-----------|
| Axis 0 | Vertical Stacking |
| Axis 1 | Horizontal Stacking |
1. Insert : ```np.insert(array, index, value, axis=none) ```
2. Append : ```np.append(array, value) ```
3. Concate : ```np.concatenate((array1,array2), axis=0)```
4. Remove : ```np.delete(array, index, axis=None)``` **Flatten array**

In [54]:
#insert in 1d array
arr = np.array([10,20,30,40,50,60])
new_arr = np.insert(arr,2,100,axis=0)
print(arr)
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [64]:
#insert in 2d array
arr_2d = np.array([[10,20,30],
                   [40,50,60]])
#insert a new row at index 1
new_ar = np.insert(arr_2d, 1, [55,33,66], axis=0)
print(arr_2d)
print(new_ar)

[[10 20 30]
 [40 50 60]]
[[10 20 30]
 [55 33 66]
 [40 50 60]]


In [67]:
#Append array
new_arr = np.append(arr_2d,[45,23,67])
print(new_arr)

[10 20 30 40 50 60 45 23 67]


In [71]:
#Concatenate Array
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
new_arr = np.concatenate((arr1,arr2),axis=0)
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [75]:
#Removing elements from an array
#1d array
arr = np.array([10,20,30,40,50])
new_arr = np.delete(arr,0)
print(new_arr)
#2d array
arr1 = np.array([[1,2,3,4,5],
                 [6,7,8,9,10]])
new_arr1 = np.delete(arr1,0, axis=0)
print(new_arr1)

[20 30 40 50]
[[ 6  7  8  9 10]]


#### Stacking
- Vertical : ```np.vstack()``` Rows-wise
- Horizontal : ```np.hstack()``` Column-wise

In [77]:
arr1 = np.array([1,2,3])
arr2 =  np.array([4,5,6])
print(np.vstack((arr1,arr2))) #vertically stack
print(np.hstack((arr1,arr2))) #horizontally stack

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


#### Splitting 
- dividing in multiple sub-arrays
- types of splitting arrays
  * **Equal** : ```np.split```
  * **Horizontally** : ```np.hsplit()```
  * **Vertically** : ```np.vsplit()```

In [85]:
arr = np.array([10,20,30,40,50,60])
print(np.split(arr,2))
arr_2d = arr.reshape(2, 3)
print(np.hsplit(arr_2d, 3))  # Splits into 3 columns
print(np.vsplit(arr_2d, 2))  # Splits into 2 rows

[array([10, 20, 30]), array([40, 50, 60])]
[array([[10],
       [40]]), array([[20],
       [50]]), array([[30],
       [60]])]
[array([[10, 20, 30]]), array([[40, 50, 60]])]


### Broadcasting

In [91]:
# Using loops
prices = [100,200,300,400,500]
discount = 10    #10% discount 
final_prices = []

for price in prices:
    final_price = price-(price*discount/100)
    final_prices.append(final_price)

print(final_prices)

[90.0, 180.0, 270.0, 360.0, 450.0]


In [92]:
# Using Broadcasting
prices = np.array([100,200,300,400,500])
discount = 10    #10% discount 
final_prices = prices - (prices*discount/100)
print(final_prices)

[ 90. 180. 270. 360. 450.]


#### How numpy handle arrays of different shapes?
1. Matching Dimensions : if have same shape
2. Expanding Single Element : ``` [1,2,3] + 10``` then output will be ```[11,12,13]```
3. Incompatible Shapes : 

In [93]:
# MATCHING DIMENSIONS
matrix = np.array([[1,2,3],[4,5,6]])    #2X3 matrix
vector = np.array([10,20,30])    #1d array
result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


In [95]:
#INCOMPATIBLE SHAPES
arr1 = np.array([[1,2,3],[4,5,6]])    #2X3 matrix
arr2 = np.array([1,3])   #shape(2,)
result = arr1+arr2
print(result)

# Solution : ```array.reshape```

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

**Vectorization (performing operation without using loops)**

In [96]:
list1 = [1,2,3]
list2 = [4,5,6]
result = [x+y for x,y in zip (list1,list2)]
print(result)

[5, 7, 9]


In [97]:
#for the same
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])
result = list1+list2
print(result)


[5 7 9]


In [98]:
arr = np.array([10,20,30])
multiplied = arr*4
print(multiplied)

[ 40  80 120]


| CONCEPT |BROADCASTING | VECTORIZATION |
|---------|--------------|---------------|
|**Conversion** | Expands the smaller arrays into larger arrays | will perform the operation on entire array. |
| **Speed** | Faster than Loops | 100 times faster than Loops |
| **Operation** | Match 1d -> 2d Array | used in matrix operation |

## Handling Missing Values
we can't compare nan (```np.isnan == np.isnn```) values directly
- **Builtins Functions**
|||
|-------|------|
|**nan** | Not a Number|
|**posinf**| Positive infinity|
|**neginf**| Negative infinity|
    * ```np.isnan(array)``` Detect missing values 
    * ```np.nan_to_num(array, nan = value) ``` Replacing nan value with other and the **default is 0**
    * ```np.isinf(array)``` Helps to detect infinite values
    * ```np.nan_to_num(arr, posinf = value, neginf=-value)``` Replacing infinite values

In [101]:
# Detect missing value
arr = np.array([1,2,np.nan,3,4,np.nan])
print(np.isnan(arr))   # missing value will show as True

[False False  True False False  True]


In [105]:
# Replacing nan value
arr = np.array([1,2,np.nan,3,4,np.nan])
cleaned_arr = np.nan_to_num(arr)    # as default value is 0
cleaned_arr_1 = np.nan_to_num(arr, nan=23)   # can put the specified value to replace null
print(cleaned_arr)
print(cleaned_arr_1)

[1. 2. 0. 3. 4. 0.]
[ 1.  2. 23.  3.  4. 23.]


In [107]:
# Dectect infinite values
arr = np.array([1,2,3,np.inf , 5,-np.inf])
print(np.isinf(arr))

[False False False  True False  True]


In [109]:
#for replacing the infinite value to finite number
arr = np.array([1,2,3,np.inf , 5,-np.inf])
cleaned_arr = np.nan_to_num(arr, posinf = 1000, neginf=-1000)      #postinf = positive infinity & neginf = negative infinity
print(cleaned_arr)

[    1.     2.     3.  1000.     5. -1000.]
