-----------
NumPy: Numerical Python

----------------
1. Array creation and storage and all functions
2. Laplace, Fourier Advance maths and linear algebra
3. Random Numbers

## Arrays: 1 to n dimensional homogenous data strucntures

In [1]:
import numpy as np

In [2]:
temp = [120, 100, 110,98, 102, 95, 80, 75]

$C = (F - 32) * \frac{5}{9}$

In [3]:
temp_C = [round((F- 32) * (5/9),2) for F in temp]
print(temp_C)

[48.89, 37.78, 43.33, 36.67, 38.89, 35.0, 26.67, 23.89]


In [4]:
# 1 dimensional

In [5]:
temp_array = np.array([120, 100, 110,98, 102, 95, 80, 75])

In [6]:
((temp_array - 32)* (5/9)).round(2)

array([48.89, 37.78, 43.33, 36.67, 38.89, 35.  , 26.67, 23.89])

str > float > int

In [7]:
np.array([2, '23', 67.09, True])

array(['2', '23', '67.09', 'True'], dtype='<U32')

In [8]:
np.array([2, '23', 67.09, True], dtype = int )

array([ 2, 23, 67,  1])

### 2 dimensional array

### Side note - Random number generation


In [9]:
np.random.randint(50, 120, (5,6) )

array([[106, 108,  85,  66,  67, 103],
       [100,  65,  58,  63, 103, 104],
       [118,  91,  73,  79, 112,  87],
       [ 65,  84,  95,  95, 111,  81],
       [101,  72,  74,  55,  75,  98]])

In [10]:
temps_fahrenheit = np.array([[85, 87, 84, 82, 86, 88],
                             [90, 91, 89, 88, 92, 93],
                             [78, 80, 79, 77, 81, 83],
                             [95, 96, 94, 93, 97, 98],
                             [88, 89, 87, 86, 90, 91]])

In [11]:
# properties of array
print("No. of dimensions : ", temps_fahrenheit.ndim)
print("Shape of the array: ", temps_fahrenheit.shape) # how many elements in each dimensional
print("Size of the array : ", temps_fahrenheit.size) # Total number of elements
print("Dtype of the array: ", temps_fahrenheit.dtype) #data type

No. of dimensions :  2
Shape of the array:  (5, 6)
Size of the array :  30
Dtype of the array:  int64


### add data for the 7th day

-----
 stack

------------
- **hstack** : concatenates 2 arrays increasing the columns
- **vstack** : concatenates 2 arrays increasing the rows

In [12]:
## add data for the 7th day
day7 = np.array([[89], [94], [82], [99], [92]])
print(day7.shape)

(5, 1)


In [13]:
np.hstack((temps_fahrenheit, day7))

array([[85, 87, 84, 82, 86, 88, 89],
       [90, 91, 89, 88, 92, 93, 94],
       [78, 80, 79, 77, 81, 83, 82],
       [95, 96, 94, 93, 97, 98, 99],
       [88, 89, 87, 86, 90, 91, 92]])

### access elements :

In [14]:
temp_array[[2, 5, 1]]

array([110,  95, 100])

In [15]:
# for 1 value
temps_fahrenheit[3, 4]

np.int64(97)

In [16]:
temps_fahrenheit

array([[85, 87, 84, 82, 86, 88],
       [90, 91, 89, 88, 92, 93],
       [78, 80, 79, 77, 81, 83],
       [95, 96, 94, 93, 97, 98],
       [88, 89, 87, 86, 90, 91]])

In [17]:
# for a complete row:
temps_fahrenheit[2]

array([78, 80, 79, 77, 81, 83])

In [18]:
# for a complete col:
temps_fahrenheit[:, 3] # 1 d

array([82, 88, 77, 93, 86])

In [19]:
# for a complete col:
temps_fahrenheit[:, [3]] # 2d

array([[82],
       [88],
       [77],
       [93],
       [86]])

In [20]:
# access elements 1 to 5

In [21]:
temp_array[1: 6]

array([100, 110,  98, 102,  95])

### Array Mathematics

In [22]:
t1 = np.array([1,2,3,4,5])
t2 = np.array([1,2,3,4,5])

In [23]:
t1 + t2

array([ 2,  4,  6,  8, 10])

In [24]:
t1 * t2

array([ 1,  4,  9, 16, 25])

In [25]:
t1 = np.array([[1, 2, 3, 4, 5], [11, 12,13, 14, 15]])
print(t1)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [26]:
t1 * 5

array([[ 5, 10, 15, 20, 25],
       [55, 60, 65, 70, 75]])

In [27]:
t2 = np.array([10,20,30,40,50])
print(t2, t2.shape)

[10 20 30 40 50] (5,)


In [28]:
print(t1.shape)

(2, 5)


In [29]:
print(t1)
print(t2)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[10 20 30 40 50]


In [30]:
t1 * t2

array([[ 10,  40,  90, 160, 250],
       [110, 240, 390, 560, 750]])

In [31]:
scores = np.random.randint(50, 101, (5, 7))
scores

array([[61, 65, 51, 71, 76, 53, 51],
       [73, 53, 69, 71, 77, 83, 75],
       [91, 79, 85, 96, 69, 57, 99],
       [75, 53, 68, 59, 69, 62, 93],
       [97, 62, 54, 84, 53, 77, 56]])

In [32]:
scores.mean()

np.float64(70.48571428571428)

In [33]:
# get the avg marks in each subject
# get the tot marks for each student

In [34]:
scores.shape

(5, 7)

In [35]:
scores

array([[61, 65, 51, 71, 76, 53, 51],
       [73, 53, 69, 71, 77, 83, 75],
       [91, 79, 85, 96, 69, 57, 99],
       [75, 53, 68, 59, 69, 62, 93],
       [97, 62, 54, 84, 53, 77, 56]])

### get the avg marks in each subject
1. Which dimension are we reducing? - reducing rows
2. Along which dimension are we calculating? - calculation for  each column

### In a 2D arry: Axis = 0 or 1
represents the index of the dimension in the shape which you are looking to reduce

In [36]:
scores.shape

(5, 7)

- index = 0 in shape --> rows
- index = 1 in shape --> columns

In [37]:
scores.mean(axis = 0)

array([79.4, 62.4, 65.4, 76.2, 68.8, 66.4, 74.8])

In [38]:
# get the tot marks for each student

In [39]:
scores.sum(axis =1 )

array([428, 501, 576, 479, 483])

## Pandas  
1. Series    : 1 dimensional labelled array like data structur
2. DataFrame : 2 dimensional labelled array like data structur

In [40]:
import pandas as pd

In [41]:
info = {'Name': ' Nimisha ', 'Age' : 35, 'Salary': 6999.99, 'Hobbies': 'Reading'}
print(info)

{'Name': ' Nimisha ', 'Age': 35, 'Salary': 6999.99, 'Hobbies': 'Reading'}


In [42]:
info_ser = pd.Series(info)
print(info_ser)

Name        Nimisha 
Age               35
Salary       6999.99
Hobbies      Reading
dtype: object


In [43]:
info_ser * 2

Name        Nimisha  Nimisha 
Age                        70
Salary               13999.98
Hobbies        ReadingReading
dtype: object

In [44]:
info_ser['Name']

' Nimisha '

In [45]:
info_ser.iloc[0]

' Nimisha '

In [46]:
ser1 = pd.Series([10,  30, 40, 50,70, 80, 90])
print(ser1)

0    10
1    30
2    40
3    50
4    70
5    80
6    90
dtype: int64


|index | value | label|
|-|-|-|
|0 | Abhay | 4|
|1 | Garima | 2|
|2 | Seema | 1|
|3 | Vaishali | 3|
|4 | Vishal | 0 |

In [47]:
ser1 = pd.Series([10,  30, 40, 50,70, 80, 90], index = ['A', 'C', 'D', 'E', 'G', 'H', 'I'])
print(ser1)

A    10
C    30
D    40
E    50
G    70
H    80
I    90
dtype: int64


In [48]:
ser2 = pd.Series([10, 20, 30, 60, 50,70, 100, 110], index = ['A', 'B', 'C', 'F', 'E' , 'G', 'J', 'K'])
print(ser2)

A     10
B     20
C     30
F     60
E     50
G     70
J    100
K    110
dtype: int64


In [49]:
ser1 + ser2

A     20.0
B      NaN
C     60.0
D      NaN
E    100.0
F      NaN
G    140.0
H      NaN
I      NaN
J      NaN
K      NaN
dtype: float64

In [50]:
ser1.add( ser2, fill_value = 9999)

A       20.0
B    10019.0
C       60.0
D    10039.0
E      100.0
F    10059.0
G      140.0
H    10079.0
I    10089.0
J    10099.0
K    10109.0
dtype: float64

## DataFrames : stack of series
- each column is a series
- each row is also a series

In [51]:
data = {
    'Country': ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
    'Capital': ['Brasília', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
    'Area_1000sqkm': [8516, 17098, 3287, 9597, 1221],
    'Population_B': [0.214, 0.143, 1.428, 1.412, 0.060],
    'GDP_per_capita_USD': [8860, 12720, 2540, 12560, 6610]
}

In [52]:
brics = pd.DataFrame(data)

In [53]:
brics

Country    Capital  Area_1000sqkm  Population_B  GDP_per_capita_USD
0        Brazil   Brasília           8516         0.214                8860
1        Russia     Moscow          17098         0.143               12720
2         India  New Delhi           3287         1.428                2540
3         China    Beijing           9597         1.412               12560
4  South Africa   Pretoria           1221         0.060                6610

### Working directory

In [54]:
pwd()

'/content'

In [55]:
import os
os.getcwd()

'/content'

In [56]:
'/Users/learnersgalaxy/Downloads/Week 16/sales_data.csv'

'/Users/learnersgalaxy/Downloads/Week 16/sales_data.csv'

In [57]:
r'C:\User\admin\downloads\sales_data.csv'

'C:\\User\\admin\\downloads\\sales_data.csv'

In [58]:
path = '~/Downloads/Week 16/sales_data.csv'

In [59]:
pd.read_csv(path)

FileNotFoundError: [Errno 2] No such file or directory: '/root/Downloads/Week 16/sales_data.csv'

In [ ]:
sales_data = pd.read_csv('sales_data.csv')
sales_data.info()

In [ ]:
?pd.read_csv