# July 20th

## functions : reusable parts of code

```python
# function definition
def function_name(parameters):
    body of the function

# function call
function_name(parameters)

```

In [3]:
def add(a, b):
    tot = a + b
    print(tot)

add(2, 4)

6


### Argument Matching 
- Positional
- Keyword

In [221]:
def example(first, second):
    print(f'first: {first}')
    print(f'Scnd : {second}')

In [223]:
example("One", "Two") # positional matching

first: One
Scnd : Two


In [225]:
example("Two", "One") # positional matching

first: Two
Scnd : One


In [227]:
example(second = 'Two', first = "One") # keyword matching

first: One
Scnd : Two


In [237]:
def welcome_message(name, greeting):
    print(f"Welcome {name}, {greeting}.")

In [239]:
welcome_message('Happy to have you', 'Alan')

Welcome Happy to have you, Alan.


In [241]:
welcome_message(greeting = 'Happy to have you', name = 'Alan')

Welcome Alan, Happy to have you.


In [243]:
welcome_message('Alan')

TypeError: welcome_message() missing 1 required positional argument: 'greeting'

### default values 

In [6]:
def welcome_message_with_default(name, greeting= 'happy to have you!'):
    print(f"Welcome {name}, {greeting}")

In [8]:
welcome_message_with_default('Alan')

Welcome Alan, happy to have you!


In [10]:
welcome_message_with_default('Alan', 'its our honour to have you here')

Welcome Alan, its our honour to have you here


---

**the default value will be picked when a value is not passed for that parameter**

---

## - Scope of data 

In [16]:
def add(a, b):
    tot = a + b
    print(tot)

add(2, 4)

6


In [18]:
print(tot)

NameError: name 'tot' is not defined

#### tot - local scope to the function 

- Global Scope: any variable/ function defined outside a function or class (anywhere in the kernel) is global scope.
- Local Scope : any variable/function defined inside a function or a class is local to that funtion or class.

In [23]:
def add(a, b):
    tot = a + b
    print(tot)

# a, b and tot are local to the function add

In [25]:
x = 100

def add(a,b):
    tot = (a + b) * x
    print(tot)

# since x is not defined in the function, hence global will be taken up

In [27]:
add(2,3)

500


---
<b>
there can same variable names for local as well as global scope, preference will be given to the envireonment from where they have been called
</b>

---

In [32]:
x = 100 # global
def add(a,b):
    x = 0.1  # local
    tot = (a + b) * x
    print(tot)

In [34]:
add(2,3)

0.5


In [36]:
print(x)

100


In [50]:
def calculate_painting_area(length, width, height):
    total_wall_area = (length + width ) * height
    return total_wall_area

In [54]:
area = calculate_painting_area(15, 12, 10)

In [56]:
total_wall_area

NameError: name 'total_wall_area' is not defined

In [58]:
area

270

In [66]:
def calculate_painting_cost(area, type_of_paint):
    if type_of_paint == 'standard':
        material_cost = 12
        labor_cost = 8
    elif type_of_paint == 'premium':
        material_cost = 18
        labor_cost = 12
    elif type_of_paint == 'luxury':
        material_cost = 25
        labor_cost = 18
    else:
        print('Invalid paint type')
        material_cost = -9999
        labor_cost = -9999
    return (material_cost +labor_cost) * area
        

In [68]:
calculate_painting_cost(area, 'premium')

8100

## Modules vs  Package vs Libraries

- modules are any **.py** extension files
- package directory containing modules/collection of modules
- library is a collection of modules performing specific task

In [74]:
# what are modules and packages and libraries available : 

In [ ]:
help("modules")

In [ ]:
# to install new modules 

## import statement
- Search for the module
1. Current directory
2. Standard library path
3. any other  path 

In [79]:
import sys

for i,p in enumerate(sys.path):
    print(f"{i}. {p}")

0. /Users/learnersgalaxy/Library/CloudStorage/OneDrive-Personal/Emeritus/IITG-DSBA March 27th/Python
1. /opt/anaconda3/lib/python312.zip
2. /opt/anaconda3/lib/python3.12
3. /opt/anaconda3/lib/python3.12/lib-dynload
4. 
5. /opt/anaconda3/lib/python3.12/site-packages
6. /opt/anaconda3/lib/python3.12/site-packages/aeosa


In [83]:
list(enumerate(['a', 'b', 'c']))

[(0, 'a'), (1, 'b'), (2, 'c')]

```python

import package-name
```
**Search for the package and create an instance in present kernel with the same name.**

In [86]:
import math

In [88]:
print(dir(math))

['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'cbrt', 'ceil', 'comb', 'copysign', 'cos', 'cosh', 'degrees', 'dist', 'e', 'erf', 'erfc', 'exp', 'exp2', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'isqrt', 'lcm', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'nextafter', 'perm', 'pi', 'pow', 'prod', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'sumprod', 'tan', 'tanh', 'tau', 'trunc', 'ulp']


In [90]:
math.log10(20)

1.3010299956639813

```python
import package-name as alias
```
**Search for the package and create an instance in present kernel with the alias name.**

In [96]:
import string as strn

In [98]:
print(dir(string))

NameError: name 'string' is not defined

In [100]:
print(dir(strn))

['Formatter', 'Template', '_ChainMap', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '_re', '_sentinel_dict', '_string', 'ascii_letters', 'ascii_lowercase', 'ascii_uppercase', 'capwords', 'digits', 'hexdigits', 'octdigits', 'printable', 'punctuation', 'whitespace']


In [102]:
strn.capwords('hello people')

'Hello People'

In [104]:
strn.digits

'0123456789'

In [106]:
strn.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

``` python

from package-name import specific functions or data attributes
```

**Searches for the package and gets only the specific function or data attributes and creates its instance inthe present runtime**

In [110]:
from string import punctuation

In [114]:
punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [117]:
from string import punctuation as punc, digits as dg

In [121]:
punc

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [123]:
dg

'0123456789'

In [127]:
import mymodule

Welcome to mymodule


# NumPy: Numerical Python
1. Array creation and storage and all functions 
2. Laplace, Fourier Advance maths and linear algebra
3. Random Numbers 

## Arrays: 1 to n dimensional homogenous data strucntures

In [131]:
import numpy as np

In [135]:
temp = [120, 100, 110,98, 102, 95, 80, 75]

$C = (F - 32) * \frac{5}{9}$

In [138]:
temp_C = [round((F- 32) * (5/9),2) for F in temp]
print(temp_C)

[48.89, 37.78, 43.33, 36.67, 38.89, 35.0, 26.67, 23.89]


In [ ]:
# 1 dimensional 

In [133]:
temp_array = np.array([120, 100, 110,98, 102, 95, 80, 75])

In [144]:
((temp_array - 32)* (5/9)).round(2)

array([48.89, 37.78, 43.33, 36.67, 38.89, 35.  , 26.67, 23.89])

str > float > int

In [147]:
np.array([2, '23', 67.09, True])

array(['2', '23', '67.09', 'True'], dtype='<U32')

In [149]:
np.array([2, '23', 67.09, True], dtype = int )

array([ 2, 23, 67,  1])

### 2 dimensional array

### Side note - Random number generation


In [162]:
np.random.randint(50, 120, (5,6) )

array([[ 65,  65,  71,  70, 105,  96],
       [113,  63, 103,  79,  83,  80],
       [ 96,  53,  82,  63,  92,  54],
       [ 82,  82, 106, 114, 103, 113],
       [112, 118,  75,  59, 103, 107]])

In [166]:
temps_fahrenheit = np.array([[85, 87, 84, 82, 86, 88],     
                             [90, 91, 89, 88, 92, 93],     
                             [78, 80, 79, 77, 81, 83],     
                             [95, 96, 94, 93, 97, 98],     
                             [88, 89, 87, 86, 90, 91]])

In [168]:
# properties of array 
print("No. of dimensions : ", temps_fahrenheit.ndim)
print("Shape of the array: ", temps_fahrenheit.shape)
print("Size of the array : ", temps_fahrenheit.size)
print("Dtype of the array: ", temps_fahrenheit.dtype)

No. of dimensions :  2
Shape of the array:  (5, 6)
Size of the array :  30
Dtype of the array:  int64


### add data for the 7th day 

### -- stack
hstack : concatenates 2 arrays increasing the columns
vstack : concatenates 2 arrays increasing the rows

In [186]:
## add data for the 7th day 
day7 = np.array([[89], [94], [82], [99], [92]])
print(day7.shape)

(5, 1)


In [180]:
np.hstack((temps_fahrenheit, day7))

array([[85, 87, 84, 82, 86, 88, 89],
       [90, 91, 89, 88, 92, 93, 94],
       [78, 80, 79, 77, 81, 83, 82],
       [95, 96, 94, 93, 97, 98, 99],
       [88, 89, 87, 86, 90, 91, 92]])

### access elements :

In [ ]:
temp_array[[2, 5, 1]]

array([110,  95, 100])

In [194]:
# for 1 value
temps_fahrenheit[3, 4]

97

In [196]:
temps_fahrenheit

array([[85, 87, 84, 82, 86, 88],
       [90, 91, 89, 88, 92, 93],
       [78, 80, 79, 77, 81, 83],
       [95, 96, 94, 93, 97, 98],
       [88, 89, 87, 86, 90, 91]])

In [198]:
# for a complete row: 
temps_fahrenheit[2]

array([78, 80, 79, 77, 81, 83])

In [202]:
# for a complete col: 
temps_fahrenheit[:, 3] # 1 d

array([82, 88, 77, 93, 86])

In [206]:
# for a complete col: 
temps_fahrenheit[:, [3]] # 2d

array([[82],
       [88],
       [77],
       [93],
       [86]])

In [208]:
# access elements 1 to 5

In [210]:
temp_array[1: 6]

array([100, 110,  98, 102,  95])

### Array Mathematics

In [213]:
t1 = np.array([1,2,3,4,5])
t2 = np.array([1,2,3,4,5])

In [215]:
t1 + t2

array([ 2,  4,  6,  8, 10])

In [217]:
t1 * t2

array([ 1,  4,  9, 16, 25])

In [219]:
t1 = np.array([[1, 2, 3, 4, 5], [11, 12,13, 14, 15]])
print(t1)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]


In [221]:
t1 * 5

array([[ 5, 10, 15, 20, 25],
       [55, 60, 65, 70, 75]])

In [223]:
t2 = np.array([10,20,30,40,50])
print(t2, t2.shape)

[10 20 30 40 50] (5,)


In [225]:
print(t1.shape)

(2, 5)


In [227]:
print(t1)
print(t2)

[[ 1  2  3  4  5]
 [11 12 13 14 15]]
[10 20 30 40 50]


In [229]:
t1 * t2 

array([[ 10,  40,  90, 160, 250],
       [110, 240, 390, 560, 750]])

In [231]:
scores = np.random.randint(50, 101, (5, 7))
scores

array([[ 62,  51,  77,  99,  55,  96,  81],
       [ 73,  69,  96,  91,  73,  86,  86],
       [ 95,  72,  76,  81,  91,  78,  50],
       [ 79,  98,  68,  75, 100,  92,  80],
       [ 66,  73,  77,  92,  84,  97,  94]])

In [233]:
scores.mean()

80.37142857142857

In [235]:
# get the avg marks in each subject 
# get the tot marks for each student

In [237]:
scores.shape

(5, 7)

In [240]:
scores

array([[ 62,  51,  77,  99,  55,  96,  81],
       [ 73,  69,  96,  91,  73,  86,  86],
       [ 95,  72,  76,  81,  91,  78,  50],
       [ 79,  98,  68,  75, 100,  92,  80],
       [ 66,  73,  77,  92,  84,  97,  94]])

### get the avg marks in each subject 
1. Which dimension are we reducing? - reducing rows
2. Along which dimension are we calculating? - calculation for  each column 

### In a 2D arry: Axis = 0 or 1
represents the index of the dimension in the shape which you are looking to reduce

In [244]:
scores.shape

(5, 7)

- index = 0 in shape --> rows
- index = 1 in shape --> columns

In [247]:
scores.mean(axis = 0)

array([75. , 72.6, 78.8, 87.6, 80.6, 89.8, 78.2])

In [249]:
# get the tot marks for each student

In [251]:
scores.sum(axis =1 )

array([521, 574, 543, 592, 583])

## Pandas  
1. Series    : 1 dimensional labelled array like data structur
2. DataFrame : 2 dimensional labelled array like data structur

In [259]:
import pandas as pd

In [261]:
info = {'Name': ' Nimisha ', 'Age' : 35, 'Salary': 6999.99, 'Hobbies': 'Reading'}
print(info)

{'Name': ' Nimisha ', 'Age': 35, 'Salary': 6999.99, 'Hobbies': 'Reading'}


In [263]:
info_ser = pd.Series(info)
print(info_ser)

Name        Nimisha 
Age               35
Salary       6999.99
Hobbies      Reading
dtype: object


In [265]:
info_ser * 2

Name        Nimisha  Nimisha 
Age                        70
Salary               13999.98
Hobbies        ReadingReading
dtype: object

In [267]:
info_ser['Name']

' Nimisha '

In [269]:
info_ser.iloc[0]

' Nimisha '

In [271]:
ser1 = pd.Series([10,  30, 40, 50,70, 80, 90])
print(ser1)

0    10
1    30
2    40
3    50
4    70
5    80
6    90
dtype: int64


|index | value | label|
|-|-|-|
|0 | Abhay | 4|
|1 | Garima | 2|
|2 | Seema | 1|
|3 | Vaishali | 3|
|4 | Vishal | 0 |

In [275]:
ser1 = pd.Series([10,  30, 40, 50,70, 80, 90], index = ['A', 'C', 'D', 'E', 'G', 'H', 'I'])
print(ser1)

A    10
C    30
D    40
E    50
G    70
H    80
I    90
dtype: int64


In [279]:
ser2 = pd.Series([10, 20, 30, 60, 50,70, 100, 110], index = ['A', 'B', 'C', 'F', 'E' , 'G', 'J', 'K'])
print(ser2)

A     10
B     20
C     30
F     60
E     50
G     70
J    100
K    110
dtype: int64


In [281]:
ser1 + ser2

A     20.0
B      NaN
C     60.0
D      NaN
E    100.0
F      NaN
G    140.0
H      NaN
I      NaN
J      NaN
K      NaN
dtype: float64

In [291]:
ser1.add( ser2, fill_value = 9999)

A       20.0
B    10019.0
C       60.0
D    10039.0
E      100.0
F    10059.0
G      140.0
H    10079.0
I    10089.0
J    10099.0
K    10109.0
dtype: float64

## DataFrames : stack of series 
- each column is a series
- each row is also a series

In [294]:
data = {
    'Country': ['Brazil', 'Russia', 'India', 'China', 'South Africa'],
    'Capital': ['Brasília', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
    'Area_1000sqkm': [8516, 17098, 3287, 9597, 1221],
    'Population_B': [0.214, 0.143, 1.428, 1.412, 0.060],
    'GDP_per_capita_USD': [8860, 12720, 2540, 12560, 6610]
}

In [298]:
brics = pd.DataFrame(data)

In [300]:
brics

Country    Capital  Area_1000sqkm  Population_B  GDP_per_capita_USD
0        Brazil   Brasília           8516         0.214                8860
1        Russia     Moscow          17098         0.143               12720
2         India  New Delhi           3287         1.428                2540
3         China    Beijing           9597         1.412               12560
4  South Africa   Pretoria           1221         0.060                6610

### Working directory 

In [303]:
pwd()

'/Users/learnersgalaxy/Library/CloudStorage/OneDrive-Personal/Emeritus/IITG-DSBA March 27th/Python'

In [305]:
import os 
os.getcwd()

'/Users/learnersgalaxy/Library/CloudStorage/OneDrive-Personal/Emeritus/IITG-DSBA March 27th/Python'

In [ ]:
'/Users/learnersgalaxy/Downloads/Week 16/sales_data.csv'

In [ ]:
r'C:\User\admin\downloads\sales_data.csv'

In [319]:
path = '~/Downloads/Week 16/sales_data.csv'

In [321]:
pd.read_csv(path)

Product  Price  Sales  Cost Region
0       Laptop   1000    800   600  North
1   Smartphone    600    500   400  South
2       Tablet    400    300   250   East
3      Monitor    300    150   100   West
4       Laptop    950    700   500   East
5   Smartphone    650    600   450  North
6   Headphones    150     80    60  South
7        Mouse     50    200    30   West
8     Keyboard    100    120    80  North
9      Monitor    350    200   150   East
10      Tablet    420    350   300  South
11  Headphones    170    140    90   West
12  Smartphone    700    650   500   East
13  Smartwatch    250    100    80  North
14      Laptop   1100    900   700  South
15       Mouse     60    220    40   East
16    Keyboard     90    110    70   West
17  Smartwatch    270    180   130   East
18      Tablet    390    320   270  North
19  Headphones    160    120    80  South
20      Laptop    950    750   600   West
21  Smartphone    620    550   420   East
22     Monitor    330    180   130  North
23  Smartwatch    240    140   110  South
24       Mouse     55    210    35   West
25      Tablet    410    330   280  South

In [329]:
sales_data = pd.read_csv('sales_data.csv')
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Product  26 non-null     object
 1   Price    26 non-null     int64 
 2   Sales    26 non-null     int64 
 3   Cost     26 non-null     int64 
 4   Region   26 non-null     object
dtypes: int64(3), object(2)
memory usage: 1.1+ KB


In [331]:
?pd.read_csv

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: '